# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', 'right', 'd']
quit = ['q', 'esc']
cd_quit = ['Q', '']
# movement
list_up = ['up', 'w']
list_down = ['down', 's']
fast_up = ['ctrl+w','-']
fast_down = ['ctrl+s','=']
page_up = ['W','']
page_down = ['S','']
# file panel control
create_new_file_panel = ['e', '']
close_file_panel = ['E', '']
next_file_panel = ['D', '']
previous_file_panel = ['A', '']
toggle_file_preview_panel = ['f', '']
open_sort_options_menu = ['o', '']
toggle_reverse_sort = ['R', '']
# change focus
focus_on_process_bar = ['p', '']
focus_on_sidebar = ['i', '']
focus_on_metadata = ['m', '']
# create file/directory and rename
file_panel_item_create = ['ctrl+n', '']
file_panel_item_rename = ['ctrl+r', '']
# file operations
copy_items = ['ctrl+c', '']
cut_items = ['ctrl+x', '']
paste_items = ['ctrl+v', '', '']
delete_items = ['ctrl+d', 'delete', '']
permanently_delete_items = ['ctrl+D', '']
# compress and extract
extract_file = ['ctrl+e', '']
compress_file = ['ctrl+a', '']
# editor
open_file_with_editor = ['x', '']
open_current_directory_with_editor = ['X', '']
# other
pinned_directory = ['P', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['v', '']
open_help_menu = ['?', '']
open_command_line = [':', '']
open_spf_prompt = ['>', '']
open_zoxide = ['z', '']
copy_path = ['ctrl+p', '']
copy_present_working_directory = ['c', '']
toggle_footer = ['F', '']
# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter', 'tab']
cancel_typing = ['ctrl+c', 'esc']
# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['a', 'left', 'backspace']
search_bar = ['/', 'tab']
# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['shift+down', 'S']
file_panel_select_mode_items_select_up = ['shift+up', 'W']
file_panel_select_all_items = ['C', '']
